version: "3"

services:
  mariadb:
    container_name: mariadb
    build: /Users/mbaioumy/Documents/Inception/mariadb/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWOR=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      -  ex:/Users/mbaioumy/Documents/Inception/mariadb/script.sh
      -  mariadb:/var/lib/mysql/
    env_file:
      - .env
    networks:
      - wordpress
    init : true
  wordpress:
    container_name: wordpress
    build: ./wordpress/
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - wordpress
    depends_on:
      - mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
    ports:
      - 9000:9000
    restart: always
    init : true
  nginx:
    container_name: nginx
    depends_on: 
      - wordpress
    build: /Users/mbaioumy/Documents/Inception/nginx/
    networks:
      - wordpress
    ports:
      - 443:443
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: always
    init : true

networks:
  wordpress:
    driver: bridge

volumes :
  ex:
  mariadb:
  wordpress:
    # driver: local
    # driver_opts:
    #   o: bind
    #   type: none
    #   device: /Users/mbaioumy/Documents/Inception/data/html